### ISSUE TITLE
How it's works ?

### ISSUE THREAD

**Issue by Ravan1190** [hawkkiller/midjourney-client#3]
Can you please provide an example for that? How to use it.

**Comment by hawkkiller** [comment]
Here the great history of dart midjourney-client starts! 😄 

Let me explain how this stuff actually works.

## Prerequesties: 

- [Discord Token](https://linuxhint.com/get-discord-token/)
- ServerId
- ChannelId

## What does actually the library do?

Well, it acts as a discord client. Thefore, it has all the possibilities the discord do (all the interactions, reactions, etc.). It invokes discord API and communicates with midjourney bot, parses messages and returns a streamed response of all the progress.

---

For now, only imagine works correctly and the library is WIP. At the moment, my main priority is setting the project up and implementing core features. It is expected that I will create all the stuff till Jun, 16.

## How to run imagine?

All the examples are in the bin/ right now, but will be moved to /example in next release.
So, to run it you need to execute 
`dart run --define=TOKEN=$(YOUR_TOKEN) --define=CHANNEL_ID=$(YOUR_CHANNEL_ID) --define=SERVER_ID=$(YOUR_SERVER_ID) bin/imagine.dart`
